module.exports = [
  // {
  //   icon: "https://play-lh.googleusercontent.com/ZU9cSsyIJZo6Oy7HTHiEPwZg0m2Crep-d5ZrfajqtsH-qgUXSqKpNA2FpPDTn-7qA5Q=w240-h480-rw",
  //   pkgId: "org.telegram.messenger",
  //   pkgName: "Telegram",
  //   version: "",
  //   download: "1B+",
  //   age: "Teen",
  //   category: "Communication",
  //   price: "Free",
  //   rating: "4.3",
  //   developer: "Telegram FZ-LLC",
  //   ios_url: "",
  //   tags: [
  //     ["4.3\nstar", "13.1M reviews"],
  //     ["1B+", "Downloads"],
  //     ["", "Mature 17+\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=org.telegram.messenger&hl=en&gl=us",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/KSuaRLiI_FlDP8cM4MzJ23ml3og5Hxb9AapaGTMZ2GgR103mvJ3AAnoOFz1yheeQBBI=w240-h480-rw",
  //   pkgId: "com.google.android.gm",
  //   pkgName: "Gmail",
  //   version: "",
  //   download: "10B+",
  //   age: "Teen",
  //   category: "Communication",
  //   price: "Free",
  //   rating: "4.2",
  //   developer: "Google LLC",
  //   ios_url: "",
  //   tags: [
  //     ["4.2\nstar", "12.6M reviews"],
  //     ["10B+", "Downloads"],
  //     ["", "Everyone\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.google.android.gm&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/bYtqbOcTYOlgc6gqZ2rwb8lptHuwlNE75zYJu6Bn076-hTmvd96HH-6v7S0YUAAJXoJN=w240-h480-rw",
  //   pkgId: "com.whatsapp",
  //   pkgName: "WhatsApp Messenger",
  //   version: "",
  //   download: "5B+",
  //   age: "Teen",
  //   category: "Communication",
  //   price: "",
  //   rating: "4.3",
  //   developer: "WhatsApp LLC",
  //   ios_url: "",
  //   tags: [
  //     ["4.3\nstar", "182M reviews"],
  //     ["5B+", "Downloads"],
  //     ["", "Editors' Choice"],
  //     ["", "Everyone\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.whatsapp&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/VYvJqGnrQiKkbbyLyMeiL-GM3go4tBIA64uVEGQazLXD4p_M3F45kHyt42o_6d5VXA=w240-h480-rw",
  //   pkgId: "com.microsoft.emmx",
  //   pkgName: "Microsoft Edge: Browse with AI",
  //   version: "",
  //   download: "50M+",
  //   age: "Teen",
  //   category: "Communication",
  //   price: "",
  //   rating: "4.7",
  //   developer: "Microsoft Corporation",
  //   ios_url: "",
  //   tags: [
  //     ["4.7\nstar", "947K reviews"],
  //     ["50M+", "Downloads"],
  //     ["", "Everyone\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.microsoft.emmx&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/0oO5sAneb9lJP6l8c6DH4aj6f85qNpplQVHmPmbbBxAukDnlO7DarDW0b-kEIHa8SQ=w240-h480-rw",
  //   pkgId: "com.discord",
  //   pkgName: "Discord: Talk, Chat & Hang Out",
  //   version: "",
  //   download: "100M+",
  //   age: "Teen",
  //   category: "Communication",
  //   price: "",
  //   rating: "4.3",
  //   developer: "Discord Inc.",
  //   ios_url: "",
  //   tags: [
  //     ["4.3\nstar", "5.51M reviews"],
  //     ["100M+", "Downloads"],
  //     ["", "Editors' Choice"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.discord&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/KxeSAjPTKliCErbivNiXrd6cTwfbqUJcbSRPe_IBVK_YmwckfMRS1VIHz-5cgT09yMo=w240-h480-rw",
  //   pkgId: "com.snapchat.android",
  //   pkgName: "Snapchat",
  //   version: "",
  //   download: "1B+",
  //   age: "Teen",
  //   category: "Communication",
  //   price: "",
  //   rating: "4.1",
  //   developer: "Snap Inc",
  //   ios_url: "",
  //   tags: [
  //     ["4.1\nstar", "33.6M reviews"],
  //     ["1B+", "Downloads"],
  //     ["", "Editors' Choice"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.snapchat.android&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/gyvvrnHT7-QD9ps1wESS6x1zJODB_MR_OFoG8usncPmR9bZiSDpKIdZjCQVKwfE4Kifg=w240-h480-rw",
  //   pkgId: "com.zzkko",
  //   pkgName: "SHEIN-Shopping Online",
  //   version: "",
  //   download: "500M+",
  //   age: "Teen",
  //   category: "Shopping",
  //   price: "",
  //   rating: "4.5",
  //   developer: "Roadget Business PTE. LTD.",
  //   ios_url: "",
  //   tags: [
  //     ["4.5\nstar", "6.13M reviews"],
  //     ["500M+", "Downloads"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.zzkko&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/giKCCPigafUbKQ1AkXVxSjQ1PggetEI96ORNKxxhQdvGAFhto71kO4zf7gZ9oOdLIQe5=w240-h480-rw",
  //   pkgId: "com.etsy.android",
  //   pkgName: "Etsy: Home, Style & Gifts",
  //   version: "",
  //   download: "10M+",
  //   age: "Teen",
  //   category: "Shopping",
  //   price: "",
  //   rating: "4.8",
  //   developer: "Etsy, Inc",
  //   ios_url: "",
  //   tags: [
  //     ["4.8\nstar", "1.43M reviews"],
  //     ["10M+", "Downloads"],
  //     ["", "Editors' Choice"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.etsy.android&hl=en&gl=us",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/31-mJUIynIfQBizOn-w1yWLKHBxVeRKA3gz348_E3K-TnuEaqCjn_-Fr9j0yQ6i0y5E=w240-h480-rw",
  //   pkgId: "com.ebay.mobile",
  //   pkgName: "eBay: Online Shopping Deals",
  //   version: "",
  //   download: "100M+",
  //   age: "Teen",
  //   category: "Shopping",
  //   price: "",
  //   rating: "4.7",
  //   developer: "eBay Mobile",
  //   ios_url: "",
  //   tags: [
  //     ["4.7\nstar", "4.65M reviews"],
  //     ["100M+", "Downloads"],
  //     ["", "Editors' Choice"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.ebay.mobile&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/Nz5sdWyh7jn4eTy_GSaRBDgaKhLC1pvYywC6fklDOlPGbopmeFN9NkqgKGjsvJMbKVEI=w240-h480-rw",
  //   pkgId: "com.einnovation.temu",
  //   pkgName: "Temu: Shop Like a Billionaire",
  //   version: "",
  //   download: "100M+",
  //   age: "Teen",
  //   category: "Shopping",
  //   price: "",
  //   rating: "4.7",
  //   developer: "Temu",
  //   ios_url: "",
  //   tags: [
  //     ["4.6\nstar", "1.48M reviews"],
  //     ["100M+", "Downloads"],
  //     ["", "Editors' Choice"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.einnovation.temu&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/KpdUynlDrYAcy_UHldmmKSgOMSRiwdJZNFNv8aNSiioCQ9miZxO4MVHIrYmdvWuSBOlo=w240-h480-rw",
  //   pkgId: "com.alibaba.aliexpresshd",
  //   pkgName: "AliExpress",
  //   version: "",
  //   download: "500M+",
  //   age: "Teen",
  //   category: "Shopping",
  //   price: "",
  //   rating: "4.5",
  //   developer: "Alibaba Mobile",
  //   ios_url: "",
  //   tags: [
  //     ["4.5\nstar", "14.4M reviews"],
  //     ["500M+", "Downloads"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.alibaba.aliexpresshd&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/8F-0kIQuTleN9DD43WlxIz-4mqmPJ3-978fr1vYF0q_QoZRrlaD3znctc4kWguHdhUCU=w240-h480-rw",
  //   pkgId: "com.meesho.supply",
  //   pkgName: "Meesho: Online Shopping App",
  //   version: "",
  //   download: "100M+",
  //   age: "Teen",
  //   category: "Shopping",
  //   price: "",
  //   rating: "4.0",
  //   developer: "Meesho",
  //   ios_url: "",
  //   tags: [
  //     ["4.0\nstar", "3.69M reviews"],
  //     ["100M+", "Downloads"],
  //     ["", "Everyone\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.meesho.supply&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/A-Rnrh0J7iKmABskTonqFAANRLGTGUg_nuE4PEMYwJavL3nPt5uWsU2WO_DSgV_mOOM=w240-h480-rw",
  //   pkgId: "com.twitter.android",
  //   pkgName: "X",
  //   version: "",
  //   download: "1B+",
  //   age: "Teen",
  //   category: "Social",
  //   price: "Free",
  //   rating: "3.8",
  //   developer: "X Corp.",
  //   ios_url: "",
  //   tags: [
  //     ["3.8\nstar", "21.5M reviews"],
  //     ["1B+", "Downloads"],
  //     ["", "Mature 17+\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.twitter.android&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/VRMWkE5p3CkWhJs6nv-9ZsLAs1QOg5ob1_3qg-rckwYW7yp1fMrYZqnEFpk0IoVP4LM=w240-h480-rw",
  //   pkgId: "com.instagram.android",
  //   pkgName: "Instagram",
  //   version: "",
  //   download: "5B+",
  //   age: "Teen",
  //   category: "Social",
  //   price: "",
  //   rating: "4.0",
  //   developer: "Instagram",
  //   ios_url: "",
  //   tags: [
  //     ["4.0\nstar", "149M reviews"],
  //     ["5B+", "Downloads"],
  //     ["", "Editors' Choice"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.instagram.android&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/KCMTYuiTrKom4Vyf0G4foetVOwhKWzNbHWumV73IXexAIy5TTgZipL52WTt8ICL-oIo=w240-h480-rw",
  //   pkgId: "com.facebook.katana",
  //   pkgName: "Facebook",
  //   version: "",
  //   download: "5B+",
  //   age: "Teen",
  //   category: "Social",
  //   price: "Free",
  //   rating: "3.4",
  //   developer: "Meta Platforms, Inc.",
  //   ios_url: "",
  //   tags: [
  //     ["3.4\nstar", "137M reviews"],
  //     ["5B+", "Downloads"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.facebook.katana&hl=en&gl=us",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/i_ZabizifODPnMgIMkyi_nIirJp73q6BbZWLkkUEiTIuHnQkuADH5xdEl2S-2LZubTA=w240-h480-rw",
  //   pkgId: "com.reddit.frontpage",
  //   pkgName: "Reddit",
  //   version: "",
  //   download: "100M+",
  //   age: "Teen",
  //   category: "Social",
  //   price: "",
  //   rating: "2.8",
  //   developer: "reddit Inc.",
  //   ios_url: "",
  //   tags: [
  //     ["2.8\nstar", "3M reviews"],
  //     ["100M+", "Downloads"],
  //     ["", "Editors' Choice"],
  //     ["", "Mature 17+\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.reddit.frontpage&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/G6jK9S77RN0laf9_6nhDo3AVxbRP9SgMmt8ZmQjKQ2hibn9xhOY-W5YFn_7stJD1CA=w240-h480-rw",
  //   pkgId: "com.instagram.barcelona",
  //   pkgName: "Threads, an Instagram app",
  //   version: "",
  //   download: "50M+",
  //   age: "Teen",
  //   category: "Social",
  //   price: "",
  //   rating: "4.1",
  //   developer: "Instagram",
  //   ios_url: "",
  //   tags: [
  //     ["4.1\nstar", "231K reviews"],
  //     ["50M+", "Downloads"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.instagram.barcelona&hl=en_US",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/BmUViDVOKNJe0GYJe22hsr7juFndRVbvr1fGmHGXqHfJjNAXjd26bfuGRQpVrpJ6YbA=w240-h480-rw",
  //   pkgId: "",
  //   pkgName: "TikTok",
  //   version: "",
  //   download: "1B+",
  //   age: "Teen",
  //   category: "Social",
  //   price: "",
  //   rating: "4.3",
  //   developer: "TikTok Pte. Ltd.",
  //   ios_url: "",
  //   tags: [
  //     ["4.3\nstar", "59.9M reviews"],
  //     ["1B+", "Downloads"],
  //     ["", "Editors' Choice"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.zhiliaoapp.musically",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/VODqBhdZXQIkQlcv_A2nAq1gPNO7fwfDlUO3UZcgcMy6jAVx05CSU-vFuVFsr9gFUuo=w240-h480-rw",
  //   pkgId: "com.wbd.stream",
  //   pkgName: "Max: Stream HBO, TV, & Movies",
  //   version: "",
  //   download: "10M+",
  //   age: "Teen",
  //   category: "Entertainment",
  //   price: "",
  //   rating: "4.8",
  //   developer: "WarnerMedia Global Digital Services, LLC",
  //   ios_url: "",
  //   tags: [
  //     ["4.7\nstar", "332K reviews"],
  //     ["10M+", "Downloads"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.wbd.stream&hl=en&gl=us",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/xoGGYH2LgLibLDBoxMg-ZE16b-RNfITw_OgXBWRAPin2FZY4FGB9QKBYApR-0rSCkQ=w240-h480-rw",
  //   pkgId: "com.disney.disneyplus",
  //   pkgName: "Disney+",
  //   version: "",
  //   download: "100M+",
  //   age: "Teen",
  //   category: "Entertainment",
  //   price: "",
  //   rating: "4.5",
  //   developer: "Disney",
  //   ios_url: "",
  //   tags: [
  //     ["4.5\nstar", "3.42M reviews"],
  //     ["100M+", "Downloads"],
  //     ["", "Editors' Choice"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.disney.disneyplus&hl=en&gl=us",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/4whGAVjZGrrlNxzheKAfBXrxggtyAb4euWLeQI8fDfVfdnFEZjE0DZTJ8DKoh64pqcIa=w240-h480-rw",
  //   pkgId: "com.hulu.plus",
  //   pkgName: "Hulu: Stream TV shows & movies",
  //   version: "",
  //   download: "50M+",
  //   age: "Teen",
  //   category: "Entertainment",
  //   price: "",
  //   rating: "4.5",
  //   developer: "Disney",
  //   ios_url: "",
  //   tags: [
  //     ["4.5\nstar", "1.02M reviews"],
  //     ["50M+", "Downloads"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.hulu.plus&hl=en&gl=us",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/Xy8NOV0EXdrbji891ShNk9HKqYWtC0__mQDrSA_SNlqcg-a0OarjX1Ny3kIxxYPoZkc=w240-h480-rw",
  //   pkgId: "com.tubitv",
  //   pkgName: "Tubi: Movies & Live TV",
  //   version: "",
  //   download: "100M+",
  //   age: "Teen",
  //   category: "Entertainment",
  //   price: "",
  //   rating: "4.8",
  //   developer: "Tubi TV",
  //   ios_url: "",
  //   tags: [
  //     ["4.7\nstar", "1.83M reviews"],
  //     ["100M+", "Downloads"],
  //     ["", "Editors' Choice"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.tubitv&hl=en&gl=us",
  //   isnot_big: false,
  // },
  // {
  //   icon: "https://play-lh.googleusercontent.com/TBRwjS_qfJCSj1m7zZB93FnpJM5fSpMA_wUlFDLxWAb45T9RmwBvQd5cWR5viJJOhkI=w240-h480-rw",
  //   pkgId: "com.netflix.mediaclient",
  //   pkgName: "Netflix",
  //   version: "",
  //   download: "1B+",
  //   age: "Teen",
  //   category: "Entertainment",
  //   price: "",
  //   rating: "4.2",
  //   developer: "Netflix, Inc.",
  //   ios_url: "",
  //   tags: [
  //     ["4.3\nstar", "14.3M reviews"],
  //     ["1B+", "Downloads"],
  //     ["", "Teen\ninfo"],
  //   ],
  //   googleplay_url:
  //     "https://play.google.com/store/apps/details?id=com.netflix.mediaclient&hl=en&gl=us",
  //   isnot_big: false,
  // },
  {
    icon: "https://play-lh.googleusercontent.com/YAKMX5YFcuE8_NogkbM7gkqrhBY6CUefbpULAVnNZLSitbo9S3Dw2FIYNqhW0d5G94Y=w240-h480-rw",
    pkgId: "com.venmo",
    pkgName: "Venmo",
    version: "",
    download: "50M+",
    age: "Teen",
    category: "Finance",
    price: "",
    rating: "4.2",
    developer: "PayPal, Inc.",
    ios_url: "",
    tags: [
      ["4.2\nstar", "720K reviews"],
      ["50M+", "Downloads"],
      ["", "Everyone\ninfo"],
    ],
    googleplay_url: "https://play.google.com/store/apps/details?id=com.venmo",
    isnot_big: false,
  },
  {
    icon: "https://play-lh.googleusercontent.com/Vw1lnV8h7LKV9P4MNfx6GJbVRMj8rl14R0Yxo1eE_UqYPk-7g6pw3RGil19kbpU3WmY=w240-h480-rw",
    pkgId: "gov.irs",
    pkgName: "IRS2Go",
    version: "",
    download: "10M+",
    age: "Teen",
    category: "Finance",
    price: "",
    rating: "3.9",
    developer: "Internal Revenue Service",
    ios_url: "",
    tags: [
      ["3.9\nstar", "72.4K reviews"],
      ["10M+", "Downloads"],
      ["", "Everyone\ninfo"],
    ],
    googleplay_url: "https://play.google.com/store/apps/details?id=gov.irs",
    isnot_big: false,
  },
  {
    icon: "https://play-lh.googleusercontent.com/laKlxh3GNIID9sdt8hIqmj12zK9z6Nqb-04wqogYkQxuA2bwFIYnbcBs5FuF7SmcnQ=w240-h480-rw",
    pkgId: "com.brisk.jpay",
    pkgName: "JPay",
    version: "",
    download: "5M+",
    age: "Teen",
    category: "Finance",
    price: "",
    rating: "4.1",
    developer: "Jpay Mobile",
    ios_url: "",
    tags: [
      ["4.1\nstar", "102K reviews"],
      ["5M+", "Downloads"],
      ["", "Everyone\ninfo"],
    ],
    googleplay_url:
      "https://play.google.com/store/apps/details?id=com.brisk.jpay",
    isnot_big: false,
  },
  {
    icon: "https://play-lh.googleusercontent.com/HArtbyi53u0jnqhnnxkQnMx9dHOERNcprZyKnInd2nrfM7Wd9ivMNTiz7IJP6-mSpwk=w240-h480-rw",
    pkgId: "com.google.android.apps.nbu.paisa.user",
    pkgName: "Google Pay: Save and Pay",
    version: "",
    download: "1B+",
    age: "Teen",
    category: "Finance",
    price: "",
    rating: "4.1",
    developer: "Google LLC",
    ios_url: "",
    tags: [
      ["4.1\nstar", "9.84M reviews"],
      ["1B+", "Downloads"],
      ["", "Everyone\ninfo"],
    ],
    googleplay_url:
      "https://play.google.com/store/apps/details?id=com.google.android.apps.nbu.paisa.user",
    isnot_big: false,
  },
  {
    icon: "https://play-lh.googleusercontent.com/awnVMi-BtmYLp6lgF19Qv0McVObf53HW7HQX7XY_cE7P6F9C6D7boWEtWqsmpaUTI68=w240-h480-rw",
    pkgId: "com.creditkarma.mobile",
    pkgName: "Intuit Credit Karma",
    version: "",
    download: "10M+",
    age: "Teen",
    category: "Finance",
    price: "",
    rating: "4.7",
    developer: "Credit Karma, LLC",
    ios_url: "",
    tags: [
      ["4.7\nstar", "2.7M reviews"],
      ["10M+", "Downloads"],
      ["", "Everyone\ninfo"],
    ],
    googleplay_url:
      "https://play.google.com/store/apps/details?id=com.creditkarma.mobile",
    isnot_big: false,
  },
  {
    icon: "https://play-lh.googleusercontent.com/5kgB8U_6961ffXmwwY-rZmc354n-5gyWW4-mHOMPxKhy5MvDU7DAUYJudvdysMwtAg=w240-h480-rw",
    pkgId: "com.greendot.walmart.prepaid",
    pkgName: "Walmart MoneyCard",
    version: "",
    download: "1M+",
    age: "Teen",
    category: "Finance",
    price: "",
    rating: "3.8",
    developer: "Green Dot",
    ios_url: "",
    tags: [
      ["3.8\nstar", "49.9K reviews"],
      ["1M+", "Downloads"],
      ["", "Everyone\ninfo"],
    ],
    googleplay_url:
      "https://play.google.com/store/apps/details?id=com.greendot.walmart.prepaid",
    isnot_big: false,
  },
  {
    icon: "https://play-lh.googleusercontent.com/tmGaBmInLjXVZIb4lWe5-LXINRP2RiY77Vg_hOLu-rxXBsY9vKC78A_A3Pkyx9vNBE8=w240-h480-rw",
    pkgId: "com.peacocktv.peacockandroid",
    pkgName: "Peacock TV: Stream TV & Movies",
    version: "",
    download: "10M+",
    age: "Teen",
    category: "Entertainment",
    price: "",
    rating: "4.5",
    developer: "Peacock TV LLC",
    ios_url: "",
    tags: [
      ["4.5\nstar", "350K reviews"],
      ["10M+", "Downloads"],
      ["", "Teen\ninfo"],
    ],
    googleplay_url:
      "https://play.google.com/store/apps/details?id=com.peacocktv.peacockandroid",
    isnot_big: false,
  },
];
